spring:
  application:
    name: homemade-eureka-service
server:
  port: 8081
  context-path: /myeureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

security:
  basic:
    enabled: true
  user:
      name: eureka
      password: eureka
