spring:
  application:
    name: homemade-eureka-service
  security:
    user:
      name: ${DEV_USER}
      password: ${DEV_PWD}

server:
  port: 8081
  servlet:
    context-path: /myeureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
