spring:
  application:
    name: homemade-eureka-service
#  security:
#    user:
#      name: eureka
#      password: eureka

server:
  port: 8081
  servlet:
    context-path: /myeureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
